# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15ab1ba0150163949a0141ac55bcd23bb225eca0f4ae10ec18c8905b7325aa52a636ea18305deb1d6c1b4972ca9b1446232d453d91be5f660123db2861707b7d

test:
  secret_key_base: 4a1dfb1b8c4caed3f953247f063fc4ff12d9dc098c6a1c1982a22f4007c8b04a8bf9910dc7d3ad1fc8f87ebe869c7ab4556cda44aab5d33a83b44353f647b23f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
